# Generated by Django 2.1.4 on 2019-01-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooks',
            name='username',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userbooks',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userbooks',
            unique_together={('username', 'book_ISBN')},
        ),
    ]
