# Generated by Django 2.1.4 on 2019-02-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190131_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooks',
            name='book_url',
            field=models.URLField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
