# Generated by Django 2.1.4 on 2019-02-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userbooks_book_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksIsbn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_ISBN', models.CharField(max_length=100, unique=True)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
