# Generated by Django 2.1.4 on 2019-02-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_booksisbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksisbn',
            name='counter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
