# Generated by Django 2.1.4 on 2019-02-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190215_1637'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbooks',
            unique_together=set(),
        ),
    ]
