# Generated by Django 2.1.4 on 2019-02-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190218_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksisbn',
            name='counter',
        ),
    ]
