# Generated by Django 2.1.4 on 2019-02-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_booksisbn_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooks',
            name='book_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
