# Generated by Django 2.1.4 on 2019-02-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_userbooks_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooks',
            name='book_rating',
            field=models.IntegerField(default=0),
        ),
    ]
